// console.log ("my name is mustafa ali mohmand")
// console.log("*****")
// console.log("*****")
// console.log("*****")
// console.log("*****")
// console.log("*****")
// console.log("*****")

console.log ("my name is mustafa ali mohmand")
console.log("*")
console.log("**")
console.log("***")
console.log("****")
console.log("*****")
console.log("******")